### ISSUE TITLE
Implement personal history on gamer's application

### ISSUE THREAD

**Issue by etsets** [etsets/wheel-of-fortune-stoiximan-2#13]
- Create a view where history (entries of spins and deposits) of a user should be displayed. Add option: Details of the history entry.
- Depending on history entry type (**spin** or **deposit**) display the appropriate view (either spin details or deposit details).
- (Low priority - only if time is sufficient) : one idea could be to use a chart of user's balance graph of i.e. latest month or statistics (percentage) of wins/losses.

**Comment by pbariamoglou** [comment]
Merged
