### ISSUE TITLE
Implement activity monitoring on admin's application

### ISSUE THREAD

**Issue by etsets** [etsets/wheel-of-fortune-stoiximan-2#14]
- Show history per user. Filter by : all, deposits, spins and sort by time desc/asc.
- Consider adding pagination (or time spans i.e. last month) in order to avoid fetching a large amount of data that could slow down performance and data display.
- (Low priority - only if time is sufficient) : one idea could be to use a chart of user's balance graph of i.e. latest month or statistics (percentage) of wins/losses.

**Comment by etsets** [comment]
Similar functionality per user also on admin's application (this is why I assigned it to you also).

**Comment by pbariamoglou** [comment]
Done
